const adminPassword = '1234';
let alumnoActual = null;
let mesSeleccionado = null;
function login(){const pass=document.getElementById('adminPass').value;if(pass===adminPassword){document.getElementById('adminPanel').style.display='block';}else{alert('Código incorrecto');}}
function registrarAlumno(){const nombre=document.getElementById('nombre').value;const familiar=document.getElementById('familiar').value;const grado=document.getElementById('grado').value;const maestro=document.getElementById('maestro').value;if(nombre&&familiar&&grado&&maestro){let alumnos=JSON.parse(localStorage.getItem('alumnos'))||[];alumnos.push({nombre,familiar,grado,maestro,pagos:{}});localStorage.setItem('alumnos',JSON.stringify(alumnos));mostrarAlumnos();document.getElementById('nombre').value='';document.getElementById('familiar').value='';document.getElementById('grado').value='';document.getElementById('maestro').value='';}else{alert('Complete todos los campos');}}
function mostrarAlumnos(){let alumnos=JSON.parse(localStorage.getItem('alumnos'))||[];const lista=document.getElementById('listaAlumnos');if(lista){lista.innerHTML='';alumnos.forEach((alumno,index)=>{const li=document.createElement('li');li.innerHTML=`${alumno.nombre} - ${alumno.grado} <button onclick='abrirModal(${index})'>+ Pago</button>`;lista.appendChild(li);});}}
function abrirModal(index){let alumnos=JSON.parse(localStorage.getItem('alumnos'))||[];alumnoActual=index;document.getElementById('alumnoSeleccionado').textContent=alumnos[index].nombre;mostrarPagos(alumnos[index]);document.getElementById('modalPago').style.display='flex';}
function cerrarModal(){document.getElementById('modalPago').style.display='none';}
function seleccionarMes(mes){mesSeleccionado=mes;}
function guardarPago(){if(mesSeleccionado&&document.getElementById('montoPago').value){let alumnos=JSON.parse(localStorage.getItem('alumnos'))||[];alumnos[alumnoActual].pagos[mesSeleccionado]=document.getElementById('montoPago').value;localStorage.setItem('alumnos',JSON.stringify(alumnos));mostrarPagos(alumnos[alumnoActual]);document.getElementById('montoPago').value='';mesSeleccionado=null;cargarTabla();}else{alert('Seleccione mes y monto');}}
function mostrarPagos(alumno){const cont=document.getElementById('pagosRegistrados');cont.innerHTML='';for(let mes in alumno.pagos){const div=document.createElement('div');div.textContent=`${mes}: L.${alumno.pagos[mes]}`;cont.appendChild(div);}}
function cargarTabla(){let alumnos=JSON.parse(localStorage.getItem('alumnos'))||[];const tbody=document.querySelector('#tablaPagos tbody');if(tbody){tbody.innerHTML='';alumnos.forEach(alumno=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${alumno.nombre}</td><td>${alumno.familiar}</td><td>${alumno.grado}</td><td>${alumno.maestro}</td>`;for(let mes of ['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic']){if(alumno.pagos[mes]){tr.innerHTML+=`<td><i class='fa-solid fa-check' style='color:green'></i> L.${alumno.pagos[mes]}</td>`;}else{tr.innerHTML+=`<td><i class='fa-solid fa-xmark' style='color:red'></i></td>`;}}tbody.appendChild(tr);});}}
window.onload=()=>{mostrarAlumnos();cargarTabla();};